#include "syscall.h"
#include "idt.h"
#include "sched.h"
#include "task.h"
#include "alfs.h"
#include "elf.h"
#include "pmm.h"
#include "uvm.h"
#include "paging.h"
#include "vga.h"
#include "pipe.h"
#include "path.h"
#include <stdint.h>

/* ── Internal fd helpers ─────────────────────────────────────────────────── */

/* Close and release one fd of current_task (IF must be 0 when called). */
static void fd_close_one(int i)
{
    task_t *t = current_task;
    if (!t->fd_table[i].used) return;
    t->fd_table[i].used = 0;
    if (t->fd_table[i].type == FD_PIPE) {
        if (t->fd_table[i].pipe_write)
            pipe_close_write(t->fd_table[i].pipe_idx);
        else
            pipe_close_read(t->fd_table[i].pipe_idx);
    }
}

/* ASM stub generated by ISR_NOERR 128 in isr.asm */
extern void isr128(void);

typedef int32_t (*syscall_fn_t)(struct regs *r);

/* ── Syscall implementations ─────────────────────────────────────────────── */

/* Staging buffer for file writes — avoids per-call kmalloc. */
static uint8_t write_buf[4096];

/* Shared file-write helper used by sys_write for any fd pointing at FD_FILE. */
static int32_t file_write(task_t *t, int fd, const char *buf, uint32_t len)
{
    int      idx = t->fd_table[fd].alfs_idx;
    uint32_t off = t->fd_table[fd].offset;

    if (off + len > sizeof(write_buf)) return -1;

    if (off > 0) {
        int got = alfs_pread(idx, write_buf, off, 0);
        if (got < 0) return -1;
    }
    for (uint32_t i = 0; i < len; i++)
        write_buf[off + i] = (uint8_t)buf[i];

    char     name[ALFS_NAME_MAX];
    uint32_t old_size;
    if (!alfs_stat(idx, name, &old_size)) return -1;
    if (alfs_write(name, write_buf, off + len) < 0) return -1;

    t->fd_table[fd].alfs_idx = alfs_find(name);
    t->fd_table[fd].offset  += len;
    return (int32_t)len;
}

static int32_t sys_write(struct regs *r)
{
    uint32_t    fd  =  r->ebx;
    const char *buf = (const char *)r->ecx;
    uint32_t    len =  r->edx;

    if (fd >= TASK_FD_MAX) return -1;
    task_t *t = current_task;

    /* If this fd has been redirected, honour the redirection. */
    if (t->fd_table[fd].used) {
        if (t->fd_table[fd].type == FD_PIPE)
            return (int32_t)pipe_write(t->fd_table[fd].pipe_idx, buf, len);
        if (t->fd_table[fd].type == FD_FILE)
            return file_write(t, (int)fd, buf, len);
    }

    /* Default for fd 1 / 2: VGA output. */
    if (fd == 1 || fd == 2) {
        for (uint32_t i = 0; i < len; i++) vga_putchar(buf[i]);
        return (int32_t)len;
    }
    return -1;
}

static int32_t sys_exit(struct regs *r)
{
    current_task->exit_code = (int32_t)r->ebx;
    /* sched_exit() will call release_pipe_fds(); no explicit cleanup needed here. */
    sched_exit();
    return 0;
}

static int32_t sys_open(struct regs *r)
{
    const char *name = (const char *)r->ebx;
    task_t *t = current_task;
    int fd = -1;
    for (int i = 3; i < TASK_FD_MAX; i++) {
        if (!t->fd_table[i].used) { fd = i; break; }
    }
    if (fd < 0) return -1;

    /* Resolve path relative to the task's cwd. */
    char resolved[64];
    path_resolve(t->cwd, name, resolved);
    int idx = alfs_find(resolved);
    if (idx < 0 || alfs_is_dir(idx)) return -1;

    t->fd_table[fd].used     = 1;
    t->fd_table[fd].type     = FD_FILE;
    t->fd_table[fd].alfs_idx = idx;
    t->fd_table[fd].offset   = 0;
    return fd;
}

static int32_t sys_read(struct regs *r)
{
    int      fd  = (int)r->ebx;
    uint8_t *buf = (uint8_t *)r->ecx;
    uint32_t len = r->edx;

    if (fd < 0 || fd >= TASK_FD_MAX) return -1;
    task_t *t = current_task;

    if (t->fd_table[fd].used) {
        if (t->fd_table[fd].type == FD_PIPE)
            return (int32_t)pipe_read(t->fd_table[fd].pipe_idx, buf, len);
        if (t->fd_table[fd].type == FD_FILE) {
            int n = alfs_pread(t->fd_table[fd].alfs_idx, buf, len,
                               t->fd_table[fd].offset);
            if (n > 0) t->fd_table[fd].offset += (uint32_t)n;
            return n;
        }
    }
    return -1;
}

static int32_t sys_close(struct regs *r)
{
    int fd = (int)r->ebx;
    if (fd < 0 || fd >= TASK_FD_MAX) return -1;
    task_t *t = current_task;
    if (!t->fd_table[fd].used) return -1;
    __asm__ volatile ("cli");
    fd_close_one(fd);
    __asm__ volatile ("sti");
    return 0;
}

static int32_t sys_brk(struct regs *r)
{
    uint32_t new_brk = r->ebx;
    task_t  *t       = current_task;

    if (new_brk == 0) return (int32_t)t->user_brk;
    if (new_brk <= t->user_brk) return (int32_t)t->user_brk;
    if (new_brk >= 0xBFFF0000u) return -1;

    uint32_t old_page = (t->user_brk + 0xFFFu) & ~0xFFFu;
    uint32_t new_page = (new_brk     + 0xFFFu) & ~0xFFFu;

    for (uint32_t va = old_page; va < new_page; va += 0x1000u) {
        uint32_t phys = pmm_alloc();
        if (!phys) return -1;
        uint8_t *p = (uint8_t *)phys;
        for (int i = 0; i < 4096; i++) p[i] = 0;
        uvm_map((uint32_t *)t->page_dir, va, phys, PAGE_USER | PAGE_WRITE);
    }

    t->user_brk = new_brk;
    return (int32_t)new_brk;
}

static int32_t sys_sleep(struct regs *r)
{
    sched_sleep(r->ebx);
    return 0;
}

/*
 * SYS_EXEC — replace the calling process's image with a new ELF from disk.
 *
 *   ebx = pointer to null-terminated filename (in user address space)
 *
 * On success this function does NOT return to the caller; instead it patches
 * the saved iret frame so that when isr_common executes iret it jumps to the
 * new ELF's entry point with a fresh user stack.
 *
 * Stack layout above struct regs (see isr.asm / idt.h):
 *   r + 52  →  saved user ESP   (uint32_t)
 *   r + 56  →  saved user SS    (uint32_t)
 * Patching r->eip and *(r+52) redirects the iret without any extra assembly.
 */
static int32_t sys_exec(struct regs *r)
{
    const char *uname = (const char *)r->ebx;

    /* Copy filename to a kernel buffer before we free user pages. */
    char kname[64];
    int  i;
    for (i = 0; i < 63 && uname[i]; i++) kname[i] = uname[i];
    kname[i] = '\0';

    /* Resolve path relative to the task's cwd. */
    char resolved[64];
    path_resolve(current_task->cwd, kname, resolved);
    for (i = 0; i < 64; i++) kname[i] = resolved[i];

    /* Free the old address space and create a fresh one. */
    uint32_t *old_pd = (uint32_t *)current_task->page_dir;
    uvm_free(old_pd);

    uint32_t *new_pd = uvm_create();
    if (!new_pd) { sched_exit(); return -1; }

    current_task->page_dir = (uint32_t)new_pd;
    /* Reload CR3 — we just freed the old directory. */
    __asm__ volatile ("mov %0, %%cr3" : : "r"((uint32_t)new_pd));

    /* Load the new ELF. */
    uint32_t entry = 0;
    if (elf_load(new_pd, kname, &entry) != 0) {
        sched_exit();
        return -1;
    }

    /* Map a fresh user stack. */
    uint32_t sp_phys = pmm_alloc();
    if (!sp_phys) { sched_exit(); return -1; }
    uint8_t *sp_page = (uint8_t *)sp_phys;
    for (int j = 0; j < 4096; j++) sp_page[j] = 0;
    uvm_map(new_pd, 0xBFFFF000, sp_phys, PAGE_USER | PAGE_WRITE);

    /* Reset per-task state: close fds ≥ 3 (preserve 0/1/2 for pipe inheritance). */
    current_task->user_brk = 0x10000000u;
    __asm__ volatile ("cli");
    for (int j = 3; j < TASK_FD_MAX; j++) fd_close_one(j);
    __asm__ volatile ("sti");

    /*
     * Patch the saved iret frame so the CPU jumps to the new entry
     * and uses the new stack after isr_common's popa + iret.
     *
     *   r->eip               = saved user EIP  (struct regs, offset 40)
     *   *(uint32_t*)(r + 52) = saved user ESP  (just above struct regs)
     */
    r->eip = entry;
    *(uint32_t *)((uint8_t *)r + sizeof(*r)) = 0xBFFFFFFC;

    return 0;   /* isr_common will iret to the new entry */
}

/*
 * SYS_FORK — duplicate the calling process.
 *
 * Returns the child's PID to the parent and 0 to the child.
 * The child is a new task that starts at the same user EIP / ESP as the
 * parent at the moment fork() was called (identical address space, copies).
 */
static int32_t sys_fork(struct regs *r)
{
    /* Clone the user address space. */
    uint32_t *child_pd = uvm_clone((uint32_t *)current_task->page_dir);
    if (!child_pd) return -1;

    /*
     * Read the saved user context from the iret frame.
     *   r->eip               = user EIP right after the int $0x80 instruction
     *   *(uint32_t*)(r + 52) = user ESP at the time of the syscall
     */
    uint32_t user_eip = r->eip;
    uint32_t user_esp = *(uint32_t *)((uint8_t *)r + sizeof(*r));

    /* Create the child task starting at the same user EIP / ESP.
       user_eax = 0 so the child's fork() returns 0. */
    task_t *child = task_create_user(user_eip, user_esp, child_pd);
    if (!child) { uvm_free(child_pd); return -1; }

    child->user_eax    = 0;           /* child sees fork() → 0   */
    child->user_brk    = current_task->user_brk;
    child->exit_code   = 0;
    child->pending_sigs = 0;
    child->waiting      = 0;
    /* fd_table: inherit open files and pipes. */
    for (int i = 0; i < TASK_FD_MAX; i++) {
        child->fd_table[i] = current_task->fd_table[i];
        if (child->fd_table[i].used && child->fd_table[i].type == FD_PIPE) {
            /* Increment pipe reference count for the new fd. */
            if (child->fd_table[i].pipe_write)
                pipe_open_write(child->fd_table[i].pipe_idx);
            else
                pipe_open_read(child->fd_table[i].pipe_idx);
        }
    }

    sched_add(child);
    return (int32_t)child->pid;   /* parent sees child's PID */
}

/*
 * SYS_WAIT — block until any direct child exits; return its PID.
 *
 *   ebx = pointer to int32_t to receive exit code, or 0
 */
static int32_t sys_wait(struct regs *r)
{
    int32_t *exit_ptr = (int32_t *)r->ebx;
    int32_t  code     = 0;
    int32_t  pid      = sched_wait(&code);
    if (exit_ptr && pid >= 0) *exit_ptr = code;
    return pid;
}

/*
 * SYS_KILL — send a signal to a task by PID.
 *
 *   ebx = target PID
 *   ecx = signal number (9 = SIGKILL)
 */
static int32_t sys_kill(struct regs *r)
{
    uint32_t pid = r->ebx;
    uint32_t sig = r->ecx;

    task_t *t = current_task->next;
    while (t != current_task) {
        if (t->pid == pid) {
            t->pending_sigs |= (1u << sig);
            return 0;
        }
        t = t->next;
    }
    return -1;   /* ESRCH */
}

/*
 * SYS_PIPE — create a kernel pipe; write two fds into user int[2].
 *
 *   ebx = pointer to int[2] to receive [read_fd, write_fd]
 */
static int32_t sys_pipe(struct regs *r)
{
    int *user_fds = (int *)r->ebx;

    int pi = pipe_alloc();
    if (pi < 0) return -1;

    task_t *t = current_task;
    int rfd = -1, wfd = -1;
    for (int i = 3; i < TASK_FD_MAX; i++) {
        if (!t->fd_table[i].used) {
            if (rfd < 0) rfd = i;
            else if (wfd < 0) { wfd = i; break; }
        }
    }
    if (rfd < 0 || wfd < 0) {
        pipe_close_read(pi);
        pipe_close_write(pi);
        return -1;
    }

    t->fd_table[rfd].used = 1; t->fd_table[rfd].type = FD_PIPE;
    t->fd_table[rfd].pipe_idx = pi; t->fd_table[rfd].pipe_write = 0;

    t->fd_table[wfd].used = 1; t->fd_table[wfd].type = FD_PIPE;
    t->fd_table[wfd].pipe_idx = pi; t->fd_table[wfd].pipe_write = 1;

    user_fds[0] = rfd;
    user_fds[1] = wfd;
    return 0;
}

/*
 * SYS_OPEN_W — create or open a file for writing.
 *
 *   ebx = pointer to null-terminated filename (user address space)
 *   ecx = 0 → overwrite (truncate to zero),  1 → append
 *
 * Returns a writable fd ≥ 3, or -1 on error.
 */
static int32_t sys_open_w(struct regs *r)
{
    const char *uname  = (const char *)r->ebx;
    int         append = (int)r->ecx;

    task_t *t = current_task;
    int fd = -1;
    for (int i = 3; i < TASK_FD_MAX; i++)
        if (!t->fd_table[i].used) { fd = i; break; }
    if (fd < 0) return -1;

    char resolved[64];
    path_resolve(t->cwd, uname, resolved);

    uint32_t start_off = 0;

    if (append) {
        int idx = alfs_find(resolved);
        if (idx >= 0) start_off = alfs_size(idx);
        else append = 0;   /* file doesn't exist yet — create fresh */
    }

    if (!append) {
        /* Truncate: write an empty file so alfs has an entry for it. */
        if (alfs_write(resolved, "", 0) < 0) return -1;
    }

    int idx = alfs_find(resolved);
    if (idx < 0) return -1;

    t->fd_table[fd].used     = 1;
    t->fd_table[fd].type     = FD_FILE;
    t->fd_table[fd].alfs_idx = idx;
    t->fd_table[fd].offset   = start_off;
    return fd;
}

static int32_t sys_getpid(struct regs *r)
{
    (void)r;
    return (int32_t)current_task->pid;
}

static int32_t sys_getppid(struct regs *r)
{
    (void)r;
    return (int32_t)current_task->parent_pid;
}

static int32_t sys_setcolor(struct regs *r)
{
    vga_set_color((unsigned char)r->ebx, (unsigned char)r->ecx);
    return 0;
}

/* ── Dispatch table ──────────────────────────────────────────────────────── */

static syscall_fn_t syscall_table[] = {
    [SYS_WRITE] = sys_write,
    [SYS_EXIT]  = sys_exit,
    [SYS_OPEN]  = sys_open,
    [SYS_READ]  = sys_read,
    [SYS_CLOSE] = sys_close,
    [SYS_BRK]   = sys_brk,
    [SYS_SLEEP] = sys_sleep,
    [SYS_EXEC]  = sys_exec,
    [SYS_FORK]  = sys_fork,
    [SYS_WAIT]     = sys_wait,
    [SYS_KILL]     = sys_kill,
    [SYS_GETPID]   = sys_getpid,
    [SYS_GETPPID]  = sys_getppid,
    [SYS_SETCOLOR] = sys_setcolor,
    [SYS_PIPE]     = sys_pipe,
    [SYS_OPEN_W]   = sys_open_w,
};

#define NSYSCALLS ((uint32_t)(sizeof(syscall_table) / sizeof(syscall_table[0])))

static void syscall_handler(struct regs *r)
{
    uint32_t n = r->eax;
    if (n >= NSYSCALLS || !syscall_table[n]) {
        r->eax = (uint32_t)-1;
        return;
    }
    r->eax = (uint32_t)syscall_table[n](r);
}

void syscall_init(void)
{
    isr_install_handler(0x80, syscall_handler);
    idt_set_gate_user(0x80, (uint32_t)isr128);
}
